// Code generated by protoc-gen-go. DO NOT EDIT.
// source: player.proto

// The package name determines the name of the directories that truss creates
// for `package echo;` truss will create the directory "echo-service".

package fdr_proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreatePlayerRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreatePlayerRequest) Reset()         { *m = CreatePlayerRequest{} }
func (m *CreatePlayerRequest) String() string { return proto.CompactTextString(m) }
func (*CreatePlayerRequest) ProtoMessage()    {}
func (*CreatePlayerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_41d803d1b635d5c6, []int{0}
}

func (m *CreatePlayerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreatePlayerRequest.Unmarshal(m, b)
}
func (m *CreatePlayerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreatePlayerRequest.Marshal(b, m, deterministic)
}
func (m *CreatePlayerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreatePlayerRequest.Merge(m, src)
}
func (m *CreatePlayerRequest) XXX_Size() int {
	return xxx_messageInfo_CreatePlayerRequest.Size(m)
}
func (m *CreatePlayerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreatePlayerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreatePlayerRequest proto.InternalMessageInfo

type CreatePlayerResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreatePlayerResponse) Reset()         { *m = CreatePlayerResponse{} }
func (m *CreatePlayerResponse) String() string { return proto.CompactTextString(m) }
func (*CreatePlayerResponse) ProtoMessage()    {}
func (*CreatePlayerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_41d803d1b635d5c6, []int{1}
}

func (m *CreatePlayerResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreatePlayerResponse.Unmarshal(m, b)
}
func (m *CreatePlayerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreatePlayerResponse.Marshal(b, m, deterministic)
}
func (m *CreatePlayerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreatePlayerResponse.Merge(m, src)
}
func (m *CreatePlayerResponse) XXX_Size() int {
	return xxx_messageInfo_CreatePlayerResponse.Size(m)
}
func (m *CreatePlayerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreatePlayerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreatePlayerResponse proto.InternalMessageInfo

type Relations struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type                 string   `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Url                  string   `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Relations) Reset()         { *m = Relations{} }
func (m *Relations) String() string { return proto.CompactTextString(m) }
func (*Relations) ProtoMessage()    {}
func (*Relations) Descriptor() ([]byte, []int) {
	return fileDescriptor_41d803d1b635d5c6, []int{2}
}

func (m *Relations) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Relations.Unmarshal(m, b)
}
func (m *Relations) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Relations.Marshal(b, m, deterministic)
}
func (m *Relations) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Relations.Merge(m, src)
}
func (m *Relations) XXX_Size() int {
	return xxx_messageInfo_Relations.Size(m)
}
func (m *Relations) XXX_DiscardUnknown() {
	xxx_messageInfo_Relations.DiscardUnknown(m)
}

var xxx_messageInfo_Relations proto.InternalMessageInfo

func (m *Relations) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Relations) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Relations) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

type Player struct {
	Id                   int32            `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string           `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Image                string           `protobuf:"bytes,3,opt,name=image,proto3" json:"image,omitempty"`
	Positions            []PlayerPosition `protobuf:"varint,4,rep,packed,name=positions,proto3,enum=fdr.PlayerPosition" json:"positions,omitempty"`
	Relations            []*Relations     `protobuf:"bytes,5,rep,name=relations,proto3" json:"relations,omitempty"`
	SeasonStats          []*SeasonStats   `protobuf:"bytes,6,rep,name=SeasonStats,proto3" json:"SeasonStats,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Player) Reset()         { *m = Player{} }
func (m *Player) String() string { return proto.CompactTextString(m) }
func (*Player) ProtoMessage()    {}
func (*Player) Descriptor() ([]byte, []int) {
	return fileDescriptor_41d803d1b635d5c6, []int{3}
}

func (m *Player) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Player.Unmarshal(m, b)
}
func (m *Player) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Player.Marshal(b, m, deterministic)
}
func (m *Player) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Player.Merge(m, src)
}
func (m *Player) XXX_Size() int {
	return xxx_messageInfo_Player.Size(m)
}
func (m *Player) XXX_DiscardUnknown() {
	xxx_messageInfo_Player.DiscardUnknown(m)
}

var xxx_messageInfo_Player proto.InternalMessageInfo

func (m *Player) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Player) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Player) GetImage() string {
	if m != nil {
		return m.Image
	}
	return ""
}

func (m *Player) GetPositions() []PlayerPosition {
	if m != nil {
		return m.Positions
	}
	return nil
}

func (m *Player) GetRelations() []*Relations {
	if m != nil {
		return m.Relations
	}
	return nil
}

func (m *Player) GetSeasonStats() []*SeasonStats {
	if m != nil {
		return m.SeasonStats
	}
	return nil
}

type SeasonStats struct {
	Season               *Season  `protobuf:"bytes,1,opt,name=season,proto3" json:"season,omitempty"`
	Stats                []*Stat  `protobuf:"bytes,2,rep,name=stats,proto3" json:"stats,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SeasonStats) Reset()         { *m = SeasonStats{} }
func (m *SeasonStats) String() string { return proto.CompactTextString(m) }
func (*SeasonStats) ProtoMessage()    {}
func (*SeasonStats) Descriptor() ([]byte, []int) {
	return fileDescriptor_41d803d1b635d5c6, []int{4}
}

func (m *SeasonStats) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SeasonStats.Unmarshal(m, b)
}
func (m *SeasonStats) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SeasonStats.Marshal(b, m, deterministic)
}
func (m *SeasonStats) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SeasonStats.Merge(m, src)
}
func (m *SeasonStats) XXX_Size() int {
	return xxx_messageInfo_SeasonStats.Size(m)
}
func (m *SeasonStats) XXX_DiscardUnknown() {
	xxx_messageInfo_SeasonStats.DiscardUnknown(m)
}

var xxx_messageInfo_SeasonStats proto.InternalMessageInfo

func (m *SeasonStats) GetSeason() *Season {
	if m != nil {
		return m.Season
	}
	return nil
}

func (m *SeasonStats) GetStats() []*Stat {
	if m != nil {
		return m.Stats
	}
	return nil
}

func init() {
	proto.RegisterType((*CreatePlayerRequest)(nil), "fdr.CreatePlayerRequest")
	proto.RegisterType((*CreatePlayerResponse)(nil), "fdr.CreatePlayerResponse")
	proto.RegisterType((*Relations)(nil), "fdr.relations")
	proto.RegisterType((*Player)(nil), "fdr.Player")
	proto.RegisterType((*SeasonStats)(nil), "fdr.SeasonStats")
}

func init() {
	proto.RegisterFile("player.proto", fileDescriptor_41d803d1b635d5c6)
}

var fileDescriptor_41d803d1b635d5c6 = []byte{
	// 340 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x92, 0xc1, 0x4e, 0xc2, 0x40,
	0x10, 0x86, 0xa5, 0xa5, 0x35, 0x9d, 0x12, 0x42, 0x16, 0x24, 0x2b, 0x31, 0x4a, 0xea, 0x85, 0x83,
	0x29, 0xb1, 0x3e, 0x81, 0x1a, 0xef, 0x64, 0xb9, 0x79, 0x21, 0x8b, 0x5d, 0xa0, 0x09, 0x74, 0xeb,
	0xee, 0x70, 0xe0, 0x49, 0x7d, 0x1d, 0xc3, 0x6c, 0xc5, 0x92, 0x70, 0xea, 0xec, 0x3f, 0xdf, 0xfc,
	0xed, 0xec, 0x5f, 0xe8, 0x54, 0x5b, 0x79, 0x50, 0x26, 0xad, 0x8c, 0x46, 0xcd, 0xfc, 0x55, 0x6e,
	0x46, 0xb1, 0x45, 0x89, 0xd6, 0x29, 0xa3, 0x8e, 0x55, 0xd2, 0xea, 0xb2, 0x3e, 0x0d, 0x1d, 0xbd,
	0xa8, 0xb4, 0x2d, 0xb0, 0xd0, 0x65, 0x4d, 0x25, 0x37, 0xd0, 0x7f, 0x37, 0x4a, 0xa2, 0x9a, 0x51,
	0x5f, 0xa8, 0xef, 0xbd, 0xb2, 0x98, 0x0c, 0x61, 0x70, 0x2e, 0xdb, 0x4a, 0x97, 0x56, 0x25, 0xaf,
	0x10, 0x19, 0xb5, 0x95, 0xe4, 0xc0, 0xba, 0xe0, 0x15, 0x39, 0x6f, 0x8d, 0x5b, 0x93, 0x48, 0x78,
	0x45, 0xce, 0x18, 0xb4, 0xf1, 0x50, 0x29, 0xee, 0x91, 0x42, 0x35, 0xeb, 0x81, 0xbf, 0x37, 0x5b,
	0xee, 0x93, 0x74, 0x2c, 0x93, 0x9f, 0x16, 0x84, 0xce, 0xb5, 0x61, 0x10, 0xfc, 0x19, 0x94, 0x72,
	0x77, 0x32, 0x38, 0xd6, 0x6c, 0x00, 0x41, 0xb1, 0x93, 0x6b, 0x55, 0x5b, 0xb8, 0x03, 0x7b, 0x86,
	0xe8, 0xb4, 0x09, 0x6f, 0x8f, 0xfd, 0x49, 0x37, 0xeb, 0xa7, 0xab, 0xdc, 0xa4, 0xce, 0x79, 0x56,
	0xf7, 0xc4, 0x3f, 0xc5, 0x9e, 0x1a, 0x9f, 0xce, 0x83, 0xb1, 0x3f, 0x89, 0xb3, 0x2e, 0x8d, 0x9c,
	0x54, 0xd1, 0xd8, 0x2d, 0x83, 0x78, 0x4e, 0xf7, 0x37, 0x3f, 0x5e, 0x29, 0x0f, 0x89, 0xef, 0x11,
	0xdf, 0xd0, 0x45, 0x13, 0x4a, 0xe6, 0x67, 0x33, 0xec, 0x11, 0x42, 0x17, 0x01, 0x6d, 0x18, 0x67,
	0x31, 0x4d, 0x3b, 0x49, 0xd4, 0x2d, 0xf6, 0x00, 0x01, 0x85, 0xc6, 0x3d, 0x7a, 0x43, 0xe4, 0x18,
	0x94, 0x28, 0x9c, 0x9e, 0xcd, 0xe0, 0xda, 0xed, 0x64, 0xd9, 0x07, 0x74, 0x9a, 0xa1, 0x30, 0x4e,
	0xf0, 0x85, 0xf8, 0x46, 0xb7, 0x17, 0x3a, 0x75, 0x82, 0x57, 0x6f, 0xf7, 0x9f, 0x77, 0xeb, 0x02,
	0x37, 0xfb, 0x65, 0xfa, 0xa5, 0x77, 0x53, 0xdc, 0x28, 0xdc, 0xc8, 0x72, 0xba, 0xca, 0xcd, 0x82,
	0x7e, 0x89, 0x65, 0x48, 0x8f, 0x97, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x37, 0x2b, 0x0f, 0x31,
	0x61, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// PlayersClient is the client API for Players service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PlayersClient interface {
	CreatePlayer(ctx context.Context, in *CreatePlayerRequest, opts ...grpc.CallOption) (*CreatePlayerResponse, error)
}

type playersClient struct {
	cc grpc.ClientConnInterface
}

func NewPlayersClient(cc grpc.ClientConnInterface) PlayersClient {
	return &playersClient{cc}
}

func (c *playersClient) CreatePlayer(ctx context.Context, in *CreatePlayerRequest, opts ...grpc.CallOption) (*CreatePlayerResponse, error) {
	out := new(CreatePlayerResponse)
	err := c.cc.Invoke(ctx, "/fdr.Players/CreatePlayer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PlayersServer is the server API for Players service.
type PlayersServer interface {
	CreatePlayer(context.Context, *CreatePlayerRequest) (*CreatePlayerResponse, error)
}

// UnimplementedPlayersServer can be embedded to have forward compatible implementations.
type UnimplementedPlayersServer struct {
}

func (*UnimplementedPlayersServer) CreatePlayer(ctx context.Context, req *CreatePlayerRequest) (*CreatePlayerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreatePlayer not implemented")
}

func RegisterPlayersServer(s *grpc.Server, srv PlayersServer) {
	s.RegisterService(&_Players_serviceDesc, srv)
}

func _Players_CreatePlayer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePlayerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlayersServer).CreatePlayer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fdr.Players/CreatePlayer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlayersServer).CreatePlayer(ctx, req.(*CreatePlayerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Players_serviceDesc = grpc.ServiceDesc{
	ServiceName: "fdr.Players",
	HandlerType: (*PlayersServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreatePlayer",
			Handler:    _Players_CreatePlayer_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "player.proto",
}
