// Code generated by protoc-gen-go. DO NOT EDIT.
// source: roster.proto

package fdr_proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RosterSlot struct {
	Position             PlayerPosition `protobuf:"varint,1,opt,name=position,proto3,enum=fdr.PlayerPosition" json:"position,omitempty"`
	Player               *Player        `protobuf:"bytes,2,opt,name=player,proto3" json:"player,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *RosterSlot) Reset()         { *m = RosterSlot{} }
func (m *RosterSlot) String() string { return proto.CompactTextString(m) }
func (*RosterSlot) ProtoMessage()    {}
func (*RosterSlot) Descriptor() ([]byte, []int) {
	return fileDescriptor_c0e3fe2c427a8672, []int{0}
}

func (m *RosterSlot) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RosterSlot.Unmarshal(m, b)
}
func (m *RosterSlot) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RosterSlot.Marshal(b, m, deterministic)
}
func (m *RosterSlot) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RosterSlot.Merge(m, src)
}
func (m *RosterSlot) XXX_Size() int {
	return xxx_messageInfo_RosterSlot.Size(m)
}
func (m *RosterSlot) XXX_DiscardUnknown() {
	xxx_messageInfo_RosterSlot.DiscardUnknown(m)
}

var xxx_messageInfo_RosterSlot proto.InternalMessageInfo

func (m *RosterSlot) GetPosition() PlayerPosition {
	if m != nil {
		return m.Position
	}
	return PlayerPosition_ALL
}

func (m *RosterSlot) GetPlayer() *Player {
	if m != nil {
		return m.Player
	}
	return nil
}

type RosterRules struct {
	Position             PlayerPosition `protobuf:"varint,1,opt,name=position,proto3,enum=fdr.PlayerPosition" json:"position,omitempty"`
	Starting             int32          `protobuf:"varint,2,opt,name=starting,proto3" json:"starting,omitempty"`
	Max                  int32          `protobuf:"varint,3,opt,name=max,proto3" json:"max,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *RosterRules) Reset()         { *m = RosterRules{} }
func (m *RosterRules) String() string { return proto.CompactTextString(m) }
func (*RosterRules) ProtoMessage()    {}
func (*RosterRules) Descriptor() ([]byte, []int) {
	return fileDescriptor_c0e3fe2c427a8672, []int{1}
}

func (m *RosterRules) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RosterRules.Unmarshal(m, b)
}
func (m *RosterRules) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RosterRules.Marshal(b, m, deterministic)
}
func (m *RosterRules) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RosterRules.Merge(m, src)
}
func (m *RosterRules) XXX_Size() int {
	return xxx_messageInfo_RosterRules.Size(m)
}
func (m *RosterRules) XXX_DiscardUnknown() {
	xxx_messageInfo_RosterRules.DiscardUnknown(m)
}

var xxx_messageInfo_RosterRules proto.InternalMessageInfo

func (m *RosterRules) GetPosition() PlayerPosition {
	if m != nil {
		return m.Position
	}
	return PlayerPosition_ALL
}

func (m *RosterRules) GetStarting() int32 {
	if m != nil {
		return m.Starting
	}
	return 0
}

func (m *RosterRules) GetMax() int32 {
	if m != nil {
		return m.Max
	}
	return 0
}

func init() {
	proto.RegisterType((*RosterSlot)(nil), "fdr.RosterSlot")
	proto.RegisterType((*RosterRules)(nil), "fdr.RosterRules")
}

func init() {
	proto.RegisterFile("roster.proto", fileDescriptor_c0e3fe2c427a8672)
}

var fileDescriptor_c0e3fe2c427a8672 = []byte{
	// 203 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x4f, 0xcd, 0x6a, 0x84, 0x30,
	0x10, 0xc6, 0x4a, 0x97, 0x65, 0x5c, 0x4a, 0x49, 0xa1, 0x88, 0x94, 0x22, 0xf6, 0xe2, 0x29, 0x82,
	0x7d, 0x83, 0x3e, 0x81, 0xa4, 0xb7, 0x5e, 0x24, 0xd6, 0xa8, 0x81, 0x68, 0x64, 0x32, 0x42, 0xfb,
	0xf6, 0xa5, 0x89, 0x95, 0x5e, 0xf7, 0x34, 0xf3, 0xfd, 0xcd, 0xc7, 0xc0, 0x05, 0xad, 0x23, 0x85,
	0x7c, 0x45, 0x4b, 0x96, 0xc5, 0x43, 0x8f, 0xd9, 0xe3, 0x6a, 0xe4, 0xb7, 0xc2, 0x76, 0xb5, 0x4e,
	0x93, 0xb6, 0x8b, 0x0b, 0x62, 0x76, 0x09, 0x7c, 0x40, 0x45, 0x07, 0x20, 0x7c, 0xf4, 0xdd, 0x58,
	0x62, 0x15, 0x9c, 0xff, 0xec, 0x69, 0x94, 0x47, 0xe5, 0x5d, 0xfd, 0xc0, 0x87, 0x1e, 0x79, 0xe3,
	0x23, 0xcd, 0x2e, 0x89, 0xc3, 0xc4, 0x5e, 0xe0, 0x14, 0xce, 0xa5, 0x37, 0x79, 0x54, 0x26, 0x75,
	0xf2, 0xcf, 0x2e, 0x76, 0xa9, 0x30, 0x90, 0x84, 0x0e, 0xb1, 0x19, 0xe5, 0xae, 0x2f, 0xc9, 0xe0,
	0xec, 0x48, 0x22, 0xe9, 0x65, 0xf4, 0x35, 0xb7, 0xe2, 0xc0, 0xec, 0x1e, 0xe2, 0x59, 0x7e, 0xa5,
	0xb1, 0xa7, 0x7f, 0xd7, 0xb7, 0xe7, 0x8f, 0xa7, 0x51, 0xd3, 0xb4, 0x75, 0xfc, 0xd3, 0xce, 0x15,
	0x4d, 0x8a, 0x26, 0xb9, 0x54, 0x43, 0x8f, 0xad, 0xff, 0xb8, 0x3b, 0xf9, 0xf1, 0xfa, 0x13, 0x00,
	0x00, 0xff, 0xff, 0x8b, 0x3e, 0x14, 0x83, 0x33, 0x01, 0x00, 0x00,
}
