// Code generated by protoc-gen-go. DO NOT EDIT.
// source: season.proto

package fdr_proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Season struct {
	Year                 string   `protobuf:"bytes,1,opt,name=year,proto3" json:"year,omitempty"`
	Type                 string   `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Stats                []*Stat  `protobuf:"bytes,3,rep,name=stats,proto3" json:"stats,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Season) Reset()         { *m = Season{} }
func (m *Season) String() string { return proto.CompactTextString(m) }
func (*Season) ProtoMessage()    {}
func (*Season) Descriptor() ([]byte, []int) {
	return fileDescriptor_9f802e8f3a685f05, []int{0}
}

func (m *Season) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Season.Unmarshal(m, b)
}
func (m *Season) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Season.Marshal(b, m, deterministic)
}
func (m *Season) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Season.Merge(m, src)
}
func (m *Season) XXX_Size() int {
	return xxx_messageInfo_Season.Size(m)
}
func (m *Season) XXX_DiscardUnknown() {
	xxx_messageInfo_Season.DiscardUnknown(m)
}

var xxx_messageInfo_Season proto.InternalMessageInfo

func (m *Season) GetYear() string {
	if m != nil {
		return m.Year
	}
	return ""
}

func (m *Season) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Season) GetStats() []*Stat {
	if m != nil {
		return m.Stats
	}
	return nil
}

func init() {
	proto.RegisterType((*Season)(nil), "fdr.season")
}

func init() {
	proto.RegisterFile("season.proto", fileDescriptor_9f802e8f3a685f05)
}

var fileDescriptor_9f802e8f3a685f05 = []byte{
	// 144 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x29, 0x4e, 0x4d, 0x2c,
	0xce, 0xcf, 0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x4e, 0x4b, 0x29, 0x92, 0xe2, 0x2e,
	0x2e, 0x49, 0x2c, 0x29, 0x86, 0x88, 0x28, 0x05, 0x72, 0xb1, 0x41, 0x54, 0x08, 0x09, 0x71, 0xb1,
	0x54, 0xa6, 0x26, 0x16, 0x49, 0x30, 0x2a, 0x30, 0x6a, 0x70, 0x06, 0x81, 0xd9, 0x20, 0xb1, 0x92,
	0xca, 0x82, 0x54, 0x09, 0x26, 0x88, 0x18, 0x88, 0x2d, 0x24, 0xcf, 0xc5, 0x0a, 0x36, 0x40, 0x82,
	0x59, 0x81, 0x59, 0x83, 0xdb, 0x88, 0x53, 0x2f, 0x2d, 0xa5, 0x48, 0x0f, 0x24, 0x12, 0x04, 0x11,
	0x77, 0x92, 0x8b, 0x92, 0x49, 0xcf, 0x2c, 0xc9, 0x28, 0x4d, 0xd2, 0x4b, 0xce, 0xcf, 0xd5, 0x2f,
	0xc9, 0x48, 0x2d, 0xc9, 0x48, 0xcc, 0xd3, 0x4f, 0x4b, 0x29, 0x8a, 0x07, 0x5b, 0x99, 0xc4, 0x06,
	0xa6, 0x8c, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0x67, 0xc6, 0x92, 0x31, 0x9b, 0x00, 0x00, 0x00,
}
