// Code generated by protoc-gen-go. DO NOT EDIT.
// source: stats.proto

package fdr_proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Stat struct {
	Id                   string         `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Active               bool           `protobuf:"varint,2,opt,name=active,proto3" json:"active,omitempty"`
	Name                 string         `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	SortOrder            int32          `protobuf:"varint,4,opt,name=sort_order,json=sortOrder,proto3" json:"sort_order,omitempty"`
	Position             PlayerPosition `protobuf:"varint,5,opt,name=position,proto3,enum=fdr.PlayerPosition" json:"position,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Stat) Reset()         { *m = Stat{} }
func (m *Stat) String() string { return proto.CompactTextString(m) }
func (*Stat) ProtoMessage()    {}
func (*Stat) Descriptor() ([]byte, []int) {
	return fileDescriptor_b4756a0aec8b9d44, []int{0}
}

func (m *Stat) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Stat.Unmarshal(m, b)
}
func (m *Stat) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Stat.Marshal(b, m, deterministic)
}
func (m *Stat) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Stat.Merge(m, src)
}
func (m *Stat) XXX_Size() int {
	return xxx_messageInfo_Stat.Size(m)
}
func (m *Stat) XXX_DiscardUnknown() {
	xxx_messageInfo_Stat.DiscardUnknown(m)
}

var xxx_messageInfo_Stat proto.InternalMessageInfo

func (m *Stat) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Stat) GetActive() bool {
	if m != nil {
		return m.Active
	}
	return false
}

func (m *Stat) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Stat) GetSortOrder() int32 {
	if m != nil {
		return m.SortOrder
	}
	return 0
}

func (m *Stat) GetPosition() PlayerPosition {
	if m != nil {
		return m.Position
	}
	return PlayerPosition_ALL
}

type StatModifier struct {
	Value                float32  `protobuf:"fixed32,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StatModifier) Reset()         { *m = StatModifier{} }
func (m *StatModifier) String() string { return proto.CompactTextString(m) }
func (*StatModifier) ProtoMessage()    {}
func (*StatModifier) Descriptor() ([]byte, []int) {
	return fileDescriptor_b4756a0aec8b9d44, []int{0, 0}
}

func (m *StatModifier) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatModifier.Unmarshal(m, b)
}
func (m *StatModifier) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatModifier.Marshal(b, m, deterministic)
}
func (m *StatModifier) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatModifier.Merge(m, src)
}
func (m *StatModifier) XXX_Size() int {
	return xxx_messageInfo_StatModifier.Size(m)
}
func (m *StatModifier) XXX_DiscardUnknown() {
	xxx_messageInfo_StatModifier.DiscardUnknown(m)
}

var xxx_messageInfo_StatModifier proto.InternalMessageInfo

func (m *StatModifier) GetValue() float32 {
	if m != nil {
		return m.Value
	}
	return 0
}

func init() {
	proto.RegisterType((*Stat)(nil), "fdr.stat")
	proto.RegisterType((*StatModifier)(nil), "fdr.stat.modifier")
}

func init() {
	proto.RegisterFile("stats.proto", fileDescriptor_b4756a0aec8b9d44)
}

var fileDescriptor_b4756a0aec8b9d44 = []byte{
	// 225 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x3c, 0x8f, 0x41, 0x6a, 0xc3, 0x30,
	0x10, 0x45, 0x91, 0x63, 0x07, 0x67, 0x0a, 0x59, 0xa8, 0x25, 0x88, 0xd0, 0x16, 0xd1, 0x95, 0x57,
	0x36, 0xb4, 0x37, 0xe8, 0x05, 0x1a, 0xb4, 0xec, 0xc6, 0x28, 0x91, 0x5c, 0x0b, 0x62, 0x8f, 0x19,
	0x4d, 0x02, 0xbd, 0x57, 0x0f, 0x58, 0xac, 0xba, 0x59, 0xcd, 0xfc, 0xff, 0x1f, 0xcc, 0x1f, 0xb8,
	0x8b, 0x6c, 0x39, 0xd6, 0x13, 0x21, 0xa3, 0x5c, 0x75, 0x8e, 0xf6, 0xbb, 0xe9, 0x6c, 0xbf, 0x3d,
	0xb5, 0x13, 0xc6, 0xc0, 0x01, 0xc7, 0x25, 0x7c, 0xf9, 0x11, 0x90, 0xcf, 0xb0, 0xdc, 0x42, 0x16,
	0x9c, 0x12, 0x5a, 0x54, 0x1b, 0x93, 0x05, 0x27, 0x77, 0xb0, 0xb6, 0x27, 0x0e, 0x57, 0xaf, 0x32,
	0x2d, 0xaa, 0xd2, 0x2c, 0x4a, 0x4a, 0xc8, 0x47, 0x3b, 0x78, 0xb5, 0x4a, 0x64, 0xda, 0xe5, 0x13,
	0x40, 0x44, 0xe2, 0x16, 0xc9, 0x79, 0x52, 0xb9, 0x16, 0x55, 0x61, 0x36, 0xb3, 0xf3, 0x31, 0x1b,
	0xb2, 0x81, 0xf2, 0xff, 0xac, 0x2a, 0xb4, 0xa8, 0xb6, 0xaf, 0xf7, 0x75, 0xe7, 0xa8, 0x3e, 0xa4,
	0x4a, 0x87, 0x25, 0x32, 0x37, 0x68, 0xaf, 0xa1, 0x1c, 0xd0, 0x85, 0x2e, 0x78, 0x92, 0x0f, 0x50,
	0x5c, 0xed, 0xf9, 0xe2, 0x53, 0xb5, 0xcc, 0xfc, 0x89, 0xf7, 0xe7, 0xcf, 0xc7, 0xaf, 0xc0, 0xfd,
	0xe5, 0x58, 0x9f, 0x70, 0x68, 0xb8, 0xf7, 0xdc, 0xdb, 0xb1, 0xe9, 0x1c, 0xb5, 0xe9, 0xad, 0xe3,
	0x3a, 0x8d, 0xb7, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x6b, 0x79, 0xb5, 0xcc, 0x09, 0x01, 0x00,
	0x00,
}
